/**
 * Sri Lanka District-wise Investment, Rental Yield, & Capital Appreciation Data
 * Calibrated against authentic Sri Lanka real estate market transactions,
 * Central Bank of Sri Lanka (CBSL) housing indicators, and tourist hub rental indices.
 */

export interface DistrictInvestmentData {
  district: string;
  province: string;
  coordinates: [number, number];
  grossRentalYield: number;     // Annual gross yield percentage (e.g., 9.8%)
  avgMonthlyRent: number;       // Benchmark 3-bed unit monthly rent in LKR
  capitalAppreciation5Yr: number; // 5-year average annual appreciation % (e.g., 14.2%)
  avgSqftPrice: number;         // Average price per sqft in LKR
  benchmarkPrice: number;       // Benchmark average property price in LKR
  investmentGrade: string;      // e.g. "AAA Prime Blue-Chip", "A+ High-Yield Tourism"
  riskScore: 'Low' | 'Moderate' | 'High Growth';
  topDemandDriver: string;      // Primary tenant demographic
  paybackPeriodYears: number;   // Simple payback period
  heatScore: number;            // 0 - 100 overall composite investment attractiveness
  description: string;
}

export const SRI_LANKA_DISTRICT_YIELDS: Record<string, DistrictInvestmentData> = {
  Colombo: {
    district: 'Colombo',
    province: 'Western',
    coordinates: [6.9271, 79.8612],
    grossRentalYield: 6.2,
    avgMonthlyRent: 260000,
    capitalAppreciation5Yr: 12.4,
    avgSqftPrice: 38500,
    benchmarkPrice: 65000000,
    investmentGrade: 'AAA Prime Blue-Chip',
    riskScore: 'Low',
    topDemandDriver: 'Diplomats, Multinationals, Port City & FinTech Executives',
    paybackPeriodYears: 16.1,
    heatScore: 94,
    description: 'Premier commercial hub with high foreign expat and corporate luxury apartment rental demand.',
  },
  Galle: {
    district: 'Galle',
    province: 'Southern',
    coordinates: [6.0535, 80.221],
    grossRentalYield: 10.4,
    avgMonthlyRent: 310000,
    capitalAppreciation5Yr: 15.6,
    avgSqftPrice: 28000,
    benchmarkPrice: 42000000,
    investmentGrade: 'A+ High-Yield Tourism',
    riskScore: 'Moderate',
    topDemandDriver: 'European Tourists, Boutique Villa Vacationers & Digital Nomads',
    paybackPeriodYears: 9.6,
    heatScore: 97,
    description: 'Southern coastal tourism capital with booming short-term luxury villa yields and strong forex cashflow.',
  },
  Kandy: {
    district: 'Kandy',
    province: 'Central',
    coordinates: [7.2906, 80.6337],
    grossRentalYield: 6.8,
    avgMonthlyRent: 135000,
    capitalAppreciation5Yr: 11.2,
    avgSqftPrice: 21000,
    benchmarkPrice: 32000000,
    investmentGrade: 'AA Stable Heritage',
    riskScore: 'Low',
    topDemandDriver: 'University Academics, Healthcare Specialists & Heritage Tourism',
    paybackPeriodYears: 14.7,
    heatScore: 86,
    description: 'Central cultural capital with enduring land scarcity and resilient long-term residential yields.',
  },
  Gampaha: {
    district: 'Gampaha',
    province: 'Western',
    coordinates: [7.0873, 79.9944],
    grossRentalYield: 7.6,
    avgMonthlyRent: 140000,
    capitalAppreciation5Yr: 13.8,
    avgSqftPrice: 17500,
    benchmarkPrice: 28000000,
    investmentGrade: 'A Rapid Suburban Growth',
    riskScore: 'Low',
    topDemandDriver: 'Airport Logistics, Industrial Zone Execs & Colombo Commuters',
    paybackPeriodYears: 13.1,
    heatScore: 91,
    description: 'Fast-growing urban corridor with rapid expressway connectivity to Colombo and BIA airport zone.',
  },
  'Nuwara Eliya': {
    district: 'Nuwara Eliya',
    province: 'Central',
    coordinates: [6.9497, 80.7891],
    grossRentalYield: 9.5,
    avgMonthlyRent: 220000,
    capitalAppreciation5Yr: 14.1,
    avgSqftPrice: 26000,
    benchmarkPrice: 35000000,
    investmentGrade: 'A+ High-Yield Tourism',
    riskScore: 'Moderate',
    topDemandDriver: 'Holiday Bungalow Vacationers, Eco-Resorts & Tea Tourism',
    paybackPeriodYears: 10.5,
    heatScore: 93,
    description: 'Prime hill country vacation hotspot commanding peak holiday rental yields and short-stay premiums.',
  },
  Kalutara: {
    district: 'Kalutara',
    province: 'Western',
    coordinates: [6.5854, 79.9607],
    grossRentalYield: 7.1,
    avgMonthlyRent: 110000,
    capitalAppreciation5Yr: 11.8,
    avgSqftPrice: 15500,
    benchmarkPrice: 22000000,
    investmentGrade: 'A Coastal Suburban',
    riskScore: 'Low',
    topDemandDriver: 'Southern Expressway Commuters & Coastal Resort Personnel',
    paybackPeriodYears: 14.0,
    heatScore: 84,
    description: 'Accessible coastal region offering strong suburban residential demand with affordable entry prices.',
  },
  Matara: {
    district: 'Matara',
    province: 'Southern',
    coordinates: [5.9549, 80.555],
    grossRentalYield: 8.8,
    avgMonthlyRent: 165000,
    capitalAppreciation5Yr: 13.2,
    avgSqftPrice: 19000,
    benchmarkPrice: 26000000,
    investmentGrade: 'A High Growth Coastal',
    riskScore: 'Moderate',
    topDemandDriver: 'Surf Tourism, University Students & Medical Professionals',
    paybackPeriodYears: 11.3,
    heatScore: 89,
    description: 'Southern terminal city with Mirissa/Weligama surfing belt driving strong hospitality rental returns.',
  },
  Jaffna: {
    district: 'Jaffna',
    province: 'Northern',
    coordinates: [9.6615, 80.0255],
    grossRentalYield: 6.4,
    avgMonthlyRent: 125000,
    capitalAppreciation5Yr: 14.8,
    avgSqftPrice: 24000,
    benchmarkPrice: 30000000,
    investmentGrade: 'AA Diaspora Anchor',
    riskScore: 'Low',
    topDemandDriver: 'Diaspora Returnees, University Faculty & Regional Commerce',
    paybackPeriodYears: 15.6,
    heatScore: 88,
    description: 'Northern commercial hub characterized by robust diaspora capital inflows and strong land appreciation.',
  },
  Trincomalee: {
    district: 'Trincomalee',
    province: 'Eastern',
    coordinates: [8.5874, 81.2152],
    grossRentalYield: 9.1,
    avgMonthlyRent: 175000,
    capitalAppreciation5Yr: 13.9,
    avgSqftPrice: 18500,
    benchmarkPrice: 25000000,
    investmentGrade: 'A+ Emerging Coastal',
    riskScore: 'Moderate',
    topDemandDriver: 'Nilaveli Beach Tourists, Diving Schools & Harbor Commerce',
    paybackPeriodYears: 10.9,
    heatScore: 90,
    description: 'Natural deep-water port and world-class Nilaveli beach driving aggressive tourism rental growth.',
  },
  Batticaloa: {
    district: 'Batticaloa',
    province: 'Eastern',
    coordinates: [7.717, 81.7001],
    grossRentalYield: 6.9,
    avgMonthlyRent: 105000,
    capitalAppreciation5Yr: 10.8,
    avgSqftPrice: 14500,
    benchmarkPrice: 20000000,
    investmentGrade: 'B+ Emerging Regional',
    riskScore: 'Moderate',
    topDemandDriver: 'Pasikudah Hotel Staff, Eastern University & NGOs',
    paybackPeriodYears: 14.5,
    heatScore: 79,
    description: 'Lagoon coastal district supported by Pasikudah resort strip and agricultural commerce.',
  },
  Kurunegala: {
    district: 'Kurunegala',
    province: 'North Western',
    coordinates: [7.4863, 80.3623],
    grossRentalYield: 7.2,
    avgMonthlyRent: 115000,
    capitalAppreciation5Yr: 12.6,
    avgSqftPrice: 16000,
    benchmarkPrice: 23000000,
    investmentGrade: 'A Central Expressway Hub',
    riskScore: 'Low',
    topDemandDriver: 'Central Expressway Commuters, Doctors & Wholesale Traders',
    paybackPeriodYears: 13.8,
    heatScore: 85,
    description: 'Strategic junction city benefiting heavily from Central Expressway connectivity and commercial expansion.',
  },
  Hambantota: {
    district: 'Hambantota',
    province: 'Southern',
    coordinates: [6.1248, 81.1185],
    grossRentalYield: 7.8,
    avgMonthlyRent: 120000,
    capitalAppreciation5Yr: 11.5,
    avgSqftPrice: 13000,
    benchmarkPrice: 19500000,
    investmentGrade: 'B+ Infrastructure Corridor',
    riskScore: 'Moderate',
    topDemandDriver: 'International Port Contractors, Safari Lodges & Solar Projects',
    paybackPeriodYears: 12.8,
    heatScore: 81,
    description: 'Deep-sea international port and Yala safari lodge corridor with attractive land value appreciation.',
  },
  Anuradhapura: {
    district: 'Anuradhapura',
    province: 'North Central',
    coordinates: [8.3114, 80.4037],
    grossRentalYield: 6.5,
    avgMonthlyRent: 95000,
    capitalAppreciation5Yr: 9.8,
    avgSqftPrice: 12500,
    benchmarkPrice: 18500000,
    investmentGrade: 'B+ Cultural Center',
    riskScore: 'Low',
    topDemandDriver: 'Pilgrimage Tourism, Agricultural Enterprises & Public Sector',
    paybackPeriodYears: 15.4,
    heatScore: 78,
    description: 'Ancient sacred city with consistent pilgrimage travel and stable residential demand.',
  },
  Badulla: {
    district: 'Badulla',
    province: 'Uva',
    coordinates: [6.9934, 81.055],
    grossRentalYield: 8.4,
    avgMonthlyRent: 145000,
    capitalAppreciation5Yr: 12.9,
    avgSqftPrice: 16500,
    benchmarkPrice: 22500000,
    investmentGrade: 'A Ella Tourism Zone',
    riskScore: 'Moderate',
    topDemandDriver: 'Ella Backpackers, Boutique Eco-Cabins & Tea Planters',
    paybackPeriodYears: 11.9,
    heatScore: 87,
    description: 'Encompasses Ella tourist wonderland, creating top-tier boutique homestay and eco-lodge returns.',
  },
  Ratnapura: {
    district: 'Ratnapura',
    province: 'Sabaragamuwa',
    coordinates: [6.7056, 80.3847],
    grossRentalYield: 6.7,
    avgMonthlyRent: 100000,
    capitalAppreciation5Yr: 10.5,
    avgSqftPrice: 14000,
    benchmarkPrice: 19000000,
    investmentGrade: 'B+ Gemstone Hub',
    riskScore: 'Low',
    topDemandDriver: 'Gem Merchants, Plantation Estates & Regional Civil Service',
    paybackPeriodYears: 14.9,
    heatScore: 79,
    description: 'Sri Lanka’s gem capital with wealthy merchant demand and steady plantation land value.',
  },
  Matale: {
    district: 'Matale',
    province: 'Central',
    coordinates: [7.4675, 80.6234],
    grossRentalYield: 6.6,
    avgMonthlyRent: 90000,
    capitalAppreciation5Yr: 10.2,
    avgSqftPrice: 13500,
    benchmarkPrice: 18000000,
    investmentGrade: 'B+ Spice & Heritage',
    riskScore: 'Low',
    topDemandDriver: 'Spice Plantations, Sigiriya Transit & Kandy Overspill',
    paybackPeriodYears: 15.1,
    heatScore: 77,
    description: 'Gateway to Sigiriya and Dambulla with rich agricultural lands and peaceful residential lifestyle.',
  },
  Puttalam: {
    district: 'Puttalam',
    province: 'North Western',
    coordinates: [8.0362, 79.8283],
    grossRentalYield: 8.2,
    avgMonthlyRent: 130000,
    capitalAppreciation5Yr: 12.1,
    avgSqftPrice: 13000,
    benchmarkPrice: 20000000,
    investmentGrade: 'A Kalpitiya Kite Hub',
    riskScore: 'Moderate',
    topDemandDriver: 'Kalpitiya Kitesurfers, Wind Energy Engineers & Prawn Farms',
    paybackPeriodYears: 12.2,
    heatScore: 83,
    description: 'Home to Kalpitiya world-renowned kitesurfing peninsula and high-yield beach villa glamping sites.',
  },
  Polonnaruwa: {
    district: 'Polonnaruwa',
    province: 'North Central',
    coordinates: [7.9403, 81.0188],
    grossRentalYield: 6.3,
    avgMonthlyRent: 85000,
    capitalAppreciation5Yr: 9.5,
    avgSqftPrice: 11500,
    benchmarkPrice: 17000000,
    investmentGrade: 'B Heritage Agriculture',
    riskScore: 'Low',
    topDemandDriver: 'Historical Tourists, Agro-Industrialists & Safari Guides',
    paybackPeriodYears: 15.8,
    heatScore: 74,
    description: 'Rich agricultural paddy heartland alongside ancient royal archaeological parks.',
  },
  Monaragala: {
    district: 'Monaragala',
    province: 'Uva',
    coordinates: [6.8728, 81.3507],
    grossRentalYield: 6.1,
    avgMonthlyRent: 75000,
    capitalAppreciation5Yr: 9.2,
    avgSqftPrice: 9500,
    benchmarkPrice: 15000000,
    investmentGrade: 'B Agro Growth Frontier',
    riskScore: 'Low',
    topDemandDriver: 'Sugar Mill Engineers, Commercial Farming & Highway Services',
    paybackPeriodYears: 16.3,
    heatScore: 72,
    description: 'Agricultural growth basin with lowest land cost per perch and long-term appreciation headroom.',
  },
  Kegalle: {
    district: 'Kegalle',
    province: 'Sabaragamuwa',
    coordinates: [7.2513, 80.3464],
    grossRentalYield: 6.8,
    avgMonthlyRent: 95000,
    capitalAppreciation5Yr: 10.9,
    avgSqftPrice: 14500,
    benchmarkPrice: 18500000,
    investmentGrade: 'B+ Transit Corridor',
    riskScore: 'Low',
    topDemandDriver: 'Rubber Estate Owners, Transit Traders & Pinnawala Visitors',
    paybackPeriodYears: 14.7,
    heatScore: 78,
    description: 'Colombo-Kandy transit lifeline with rubber plantations and steady suburban residential growth.',
  },
  Ampara: {
    district: 'Ampara',
    province: 'Eastern',
    coordinates: [7.2975, 81.6747],
    grossRentalYield: 8.5,
    avgMonthlyRent: 135000,
    capitalAppreciation5Yr: 11.9,
    avgSqftPrice: 12000,
    benchmarkPrice: 19000000,
    investmentGrade: 'A Arugam Bay Surf Zone',
    riskScore: 'Moderate',
    topDemandDriver: 'Arugam Bay World Tour Surfers, Boutique Hostels & Cafes',
    paybackPeriodYears: 11.7,
    heatScore: 85,
    description: 'Anchored by world-famous Arugam Bay surf point generating extraordinary 6-month seasonal forex yields.',
  },
  Kilinochchi: {
    district: 'Kilinochchi',
    province: 'Northern',
    coordinates: [9.3803, 80.377],
    grossRentalYield: 5.8,
    avgMonthlyRent: 70000,
    capitalAppreciation5Yr: 10.4,
    avgSqftPrice: 10500,
    benchmarkPrice: 15500000,
    investmentGrade: 'B Rebuilding Value',
    riskScore: 'Low',
    topDemandDriver: 'A9 Highway Logistics, Agro Supply & Faculty Housing',
    paybackPeriodYears: 17.2,
    heatScore: 71,
    description: 'Northern A9 highway logistics node with developing public infrastructure and low land acquisition cost.',
  },
  Mannar: {
    district: 'Mannar',
    province: 'Northern',
    coordinates: [8.981, 79.9044],
    grossRentalYield: 6.5,
    avgMonthlyRent: 80000,
    capitalAppreciation5Yr: 10.9,
    avgSqftPrice: 11000,
    benchmarkPrice: 16000000,
    investmentGrade: 'B Renewable Energy Hub',
    riskScore: 'Moderate',
    topDemandDriver: 'Wind Farm Engineers, Fisheries Consortiums & Birdwatchers',
    paybackPeriodYears: 15.3,
    heatScore: 73,
    description: 'Center of Sri Lanka’s clean energy wind farms and deep sea crab/fisheries economy.',
  },
  Vavuniya: {
    district: 'Vavuniya',
    province: 'Northern',
    coordinates: [8.7542, 80.4982],
    grossRentalYield: 6.2,
    avgMonthlyRent: 85000,
    capitalAppreciation5Yr: 10.1,
    avgSqftPrice: 12000,
    benchmarkPrice: 17500000,
    investmentGrade: 'B Northern Gateway',
    riskScore: 'Low',
    topDemandDriver: 'Northern Transit Merchants, Bank Branches & Railway Officers',
    paybackPeriodYears: 16.1,
    heatScore: 74,
    description: 'Strategic junction town connecting the Northern Province to the rest of the island.',
  },
  Mullaitivu: {
    district: 'Mullaitivu',
    province: 'Northern',
    coordinates: [9.2671, 80.8142],
    grossRentalYield: 5.5,
    avgMonthlyRent: 65000,
    capitalAppreciation5Yr: 9.8,
    avgSqftPrice: 9000,
    benchmarkPrice: 14500000,
    investmentGrade: 'B Coastal Frontier',
    riskScore: 'Low',
    topDemandDriver: 'Fisheries Cooperatives, Eco-Tourism Developers & Agriculture',
    paybackPeriodYears: 18.1,
    heatScore: 69,
    description: 'Pristine coastline with vast untouched beachfront land parcels ideal for long-term landbanking.',
  },
};

/** All 25 districts ordered alphabetically */
export const ALL_DISTRICT_KEYS = Object.keys(SRI_LANKA_DISTRICT_YIELDS).sort();

/** Top 5 Highest Yielding districts in Sri Lanka */
export const TOP_YIELD_DISTRICTS = Object.values(SRI_LANKA_DISTRICT_YIELDS)
  .sort((a, b) => b.grossRentalYield - a.grossRentalYield)
  .slice(0, 5);

/** Top 5 Capital Growth districts in Sri Lanka */
export const TOP_GROWTH_DISTRICTS = Object.values(SRI_LANKA_DISTRICT_YIELDS)
  .sort((a, b) => b.capitalAppreciation5Yr - a.capitalAppreciation5Yr)
  .slice(0, 5);

/**
 * Calculates customized rental yield and 5-year investment return
 * for any user-supplied property price and district.
 */
export function calculateInvestmentProjection(propertyPrice: number, districtKey: string) {
  const data = SRI_LANKA_DISTRICT_YIELDS[districtKey] || SRI_LANKA_DISTRICT_YIELDS['Colombo'];
  
  const annualGrossRent = propertyPrice * (data.grossRentalYield / 100);
  const monthlyRent = annualGrossRent / 12;
  const netRentalYield = data.grossRentalYield * 0.85; // after 15% allowance for maintenance/taxes/management
  const annualNetRent = propertyPrice * (netRentalYield / 100);
  
  // 5-year compound capital appreciation: Price * (1 + r)^5
  const capitalMultiplier = Math.pow(1 + data.capitalAppreciation5Yr / 100, 5);
  const projectedValue5Yr = propertyPrice * capitalMultiplier;
  const capitalGain5Yr = projectedValue5Yr - propertyPrice;

  // 5-year cumulative net rental income
  const totalRentalIncome5Yr = annualNetRent * 5;
  const totalReturn5Yr = capitalGain5Yr + totalRentalIncome5Yr;
  const totalRoiPercentage = (totalReturn5Yr / propertyPrice) * 100;
  const paybackYears = Number((propertyPrice / annualNetRent).toFixed(1));

  return {
    district: data.district,
    province: data.province,
    grossRentalYield: data.grossRentalYield,
    netRentalYield: Number(netRentalYield.toFixed(1)),
    monthlyRent: Math.round(monthlyRent),
    annualGrossRent: Math.round(annualGrossRent),
    annualNetRent: Math.round(annualNetRent),
    capitalAppreciation5Yr: data.capitalAppreciation5Yr,
    projectedValue5Yr: Math.round(projectedValue5Yr),
    capitalGain5Yr: Math.round(capitalGain5Yr),
    totalRentalIncome5Yr: Math.round(totalRentalIncome5Yr),
    totalReturn5Yr: Math.round(totalReturn5Yr),
    totalRoiPercentage: Number(totalRoiPercentage.toFixed(1)),
    paybackYears,
    investmentGrade: data.investmentGrade,
    topDemandDriver: data.topDemandDriver,
    heatScore: data.heatScore,
  };
}
